version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 capstone.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web