# Use a Node.js image
FROM node:20.12.2

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json from the root
COPY package*.json ./
COPY tsconfig.json ./
COPY tailwind.config.js ./
COPY postcss.config.js ./
COPY .stylelintrc.json ./
COPY .babelrc ./
COPY .eslintrc ./

# Install dependencies
RUN npm install

# Copy the frontend source code
COPY frontend/ .

# Build the frontend

# Serve the frontend
CMD ["npm", "run", "dev"]