version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 capstone.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - frontend
    networks:
      - capstone_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9091:9091"
    volumes:
      - ./frontend:/app/frontend
    networks:
      - capstone_network

  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web
      - frontend
    networks:
      - capstone_network

networks:
  capstone_network:
    driver: bridge
