version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - staticfiles:/app/staticfiles
    expose:
      - "8000"
      - "9091"
    networks:
      - capstone_network
  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/app/staticfiles
    depends_on:
      - web
    networks:
      - capstone_network

networks:
  capstone_network:
    driver: bridge

volumes:
  staticfiles: